In [1]:
import numpy as np
import matplotlib.pyplot as plt

- Problem: Create the following matrix in python and assign it to __x3__ <br>
$\begin{bmatrix}1 & 2 & 3 & 4 & 5\\6 & 7 & 8 & 9 & 10\end{bmatrix}$

In [2]:
x3 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

- Determine the size of _x3_

In [3]:
np.shape(x3)

(2, 5)

- If we use np.size(x3) what result would we obtain?

In [4]:
np.size(x3)

10

_Problem_ : Here something different I want you to think about. If I run the following code, it generates a vector __x1__
    <br><br>
    x1 = np.linespace(1, 6, 6)
    <br><br>
    - How many elements are in _x1_<br>
    - Write a code to access the first element in _x1_<br>
    - Write a code to access the last element in _x1_<br>

In [5]:
x1 = np.linspace(1, 6, 6)
print(x1)

[1. 2. 3. 4. 5. 6.]


- How many elements are in x1?

In [6]:
print(len(x1))

6


Or

In [7]:
print(np.size(x1))

6


- Write a code to access the first element in _x1_.

In [8]:
print(x1[0])

1.0


- Write a code to access the last element in _x1_.

In [9]:
print(x1[-1])

6.0


- Given the following vector _x_, extract the numbers that satisfy the conditions $2\leq{x}\leq9$

In [10]:
x = np.linspace(0, 10, 11)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [11]:
x[2:10]

array([2., 3., 4., 5., 6., 7., 8., 9.])

For the above code,<br><br>
- 2 states hat we start at second element in the list, don't forget that the slicing index starts at 0
- 10 states that we end at the 10th element in the list, but not include it.
- The colon in the middle states that we want to use slicing to get objects in the list

In [12]:
x[2:11]

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In the above code<br><br>
- Very similar to the previous code, except it will also include the 12th element, or 11th place in the list

In [13]:
x[1:11:2]

array([1., 3., 5., 7., 9.])

In the above code<br><br>
- the 1 in the beginning means that it will slice starting at the 2nd element, or 1st place in the list<br>
- 11 represents the ending position for the slice operation.<br>
- the second colon means that the slicing will have a pattern to it, causing the following number to specify this<br>
- the 2 stands for how many places that will be skipped each iteration. This causes the last element, or 10., to be skipped

In [14]:
x[::-1]

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0.])

In the above code<br><br>
- Since there is no value before the first colon, it will start at the beginning index of the list
- Since  there is no value after the first colon, it will go all the way to the end of the list
- __-1__ makes the index to increment every time by -1, causing it to traverse the list by going backwards

Given the xnew = [1, 2, 3, 4], write a code to sum the numbers in xnew

In [15]:
xnew = [1, 2, 3, 4]
sum1 = np.sum(xnew)
print(sum1)

10


or

In [16]:
sum2 = sum(xnew)
print(sum2)

10


__Example: Finding the slope of a line.__<br>
Given the equation $y = 5x$, plot the graph for $0\leq{x}\leq10$ and write a code to determine the slope.

In [17]:
xval = np.linspace(0, 10, 11)
print(xval)
yval = 5*xval
print(yval)

slope = (yval[1]-yval[0])/(xval[1]-xval[0])
print(slope)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
5.0


Or

In [18]:
xval = np.linspace(0,10,11)
yval = xval*5

nvals = xval.size

slopes = (yval[1:nvals] - yval[0:nvals-1])/(xval[1:nvals] - xval[0:nvals-1])

print(np.min(slopes))
print(np.max(slopes))
print(np.mean(slopes))

print(slopes)

5.0
5.0
5.0
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
